CREATE TABLE IF NOT EXISTS items (
	id INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(120) NOT NULL,
	expiry_date DATETIME NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bids (
	bId INT NOT NULL AUTO_INCREMENT,
	iId INT NOT NULL,
	name VARCHAR(120) NOT NULL,
	amount INT NOT NULL,
	PRIMARY KEY (bId),
  FOREIGN KEY(iId) references items(id)
);